{"uid":"f673b2f24ebc4f14","name":"test_attachments","fullName":"tests.test_check_issue#test_attachments","historyId":"d1d0eb314b360fbd08296ae1ab707750","time":{"start":1657734953443,"stop":1657734953443,"duration":0},"status":"broken","statusMessage":"RuntimeError: No webdriver is bound to current process: 2253. You need to call .open(url) first.","statusTrace":"def test_attachments():\n        allure.attach(\"Text content\", name=\"Text\", attachment_type=attachment_type.TEXT)\n        allure.attach(\"<h1>Hello, world</h1>\", name=\"Html\", attachment_type=attachment_type.HTML)\n        allure.attach(json.dumps({\"first\": 1, \"second\": 2}), name=\"Json\", attachment_type=attachment_type.JSON)\n>       allure.attach(browser.driver.get_screenshot_as_png(), name=\"Screenshot\", attachment_type=attachment_type.PNG)\n\ntest_attachments.py:12: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/selene/support/shared/browser.py:86: in driver\n    webdriver: WebDriver = self.config.driver\n/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/selene/support/shared/config.py:268: in driver\n    return self._source.instance\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selene.support.shared.config._LazyDriver object at 0x7f6ea0e27100>\n\n    @property\n    def instance(self) -> WebDriver:\n        if self._closed:\n            raise RuntimeError(\n                'Webdriver has been closed. '\n                'You need to call open(url) '\n                'to open a browser again.'\n            )\n    \n        if not self.has_webdriver_started():\n>           raise RuntimeError(\n                f'No webdriver is bound to current process: '\n                f'{multiprocessing.current_process().pid}. '\n                f'You need to call .open(url) first.'\n            )\nE           RuntimeError: No webdriver is bound to current process: 2253. You need to call .open(url) first.\n\n/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/selene/support/shared/config.py:98: RuntimeError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"broken","statusMessage":"RuntimeError: No webdriver is bound to current process: 2253. You need to call .open(url) first.","statusTrace":"def test_attachments():\n        allure.attach(\"Text content\", name=\"Text\", attachment_type=attachment_type.TEXT)\n        allure.attach(\"<h1>Hello, world</h1>\", name=\"Html\", attachment_type=attachment_type.HTML)\n        allure.attach(json.dumps({\"first\": 1, \"second\": 2}), name=\"Json\", attachment_type=attachment_type.JSON)\n>       allure.attach(browser.driver.get_screenshot_as_png(), name=\"Screenshot\", attachment_type=attachment_type.PNG)\n\ntest_attachments.py:12: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/selene/support/shared/browser.py:86: in driver\n    webdriver: WebDriver = self.config.driver\n/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/selene/support/shared/config.py:268: in driver\n    return self._source.instance\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selene.support.shared.config._LazyDriver object at 0x7f6ea0e27100>\n\n    @property\n    def instance(self) -> WebDriver:\n        if self._closed:\n            raise RuntimeError(\n                'Webdriver has been closed. '\n                'You need to call open(url) '\n                'to open a browser again.'\n            )\n    \n        if not self.has_webdriver_started():\n>           raise RuntimeError(\n                f'No webdriver is bound to current process: '\n                f'{multiprocessing.current_process().pid}. '\n                f'You need to call .open(url) first.'\n            )\nE           RuntimeError: No webdriver is bound to current process: 2253. You need to call .open(url) first.\n\n/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/selene/support/shared/config.py:98: RuntimeError","steps":[],"attachments":[{"uid":"105a85a3056599bf","name":"Text","source":"105a85a3056599bf.txt","type":"text/plain","size":12},{"uid":"152c14aa57723ee1","name":"Html","source":"152c14aa57723ee1.html","type":"text/html","size":21},{"uid":"514f3a6f11274427","name":"Json","source":"514f3a6f11274427.json","type":"application/json","size":25}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":true,"hasContent":true},"afterStages":[],"labels":[{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_check_issue"},{"name":"host","value":"fv-az445-841"},{"name":"thread","value":"2253-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_check_issue"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"f673b2f24ebc4f14.json","parameterValues":[]}